# typed: false
# frozen_string_literal: true

module Swill
  module Ruby2JS
    # Generated Sorbet artifacts: RBIs for declared accessors and typed probes
    # for declaration expressions. Neither is executed or shipped.
    class Compiler
        def rbi
          lines = ["# typed: true", "# Generated by the spike compiler. Do not edit."]
          knowledge.local.each do |entry|
            mixin = entry["kind"] == "mixin"
            properties = mixin ? entry["included_properties"] : entry["properties"]
            unless mixin && properties.empty?
              declaration = "#{mixin ? 'module' : 'class'} #{entry['name']}"
              if !mixin && entry["parent"]
                declaration << " < #{knowledge.resolve(entry['parent'], entry['scope'])}"
              end
              lines << declaration
              lines << "  extend T::Sig"
              properties.each do |property|
                name, type = property.values_at("name", "type")
                lines << "  sig { returns(#{type}) }"
                lines << "  def #{name}; end"
                unless property["computed"]
                  lines << "  sig { params(value: #{type}).returns(#{type}) }"
                  lines << "  def #{name}=(value); end"
                end
              end
              lines << "end"
            end
            if mixin && entry["extends_class_methods"]
              lines << "module #{entry['name']}::ClassMethods"
              lines << "  extend T::Sig"
              entry["registries"].each do |registry|
                collection = registry["initial"] == "array" ? "T::Array[T.untyped]" : "T::Hash[T.untyped, T.untyped]"
                lines << "  sig { returns(#{collection}) }"
                lines << "  def #{registry['name']}; end"
              end
              entry["settings"].each do |name|
                lines << "  sig { params(values: T.untyped).returns(T.untyped) }"
                lines << "  def #{name}(*values); end"
              end
              lines << "end"
            end
          end
          lines.join("\n") + "\n"
        end

        # Sorbet can bind DSL blocks to the instance, but a single property macro
        # signature cannot express the different return type of every declaration.
        # Check each expression as a typed instance method as well. These methods
        # are never loaded on MRI or emitted into JavaScript.
        def type_probes
          lines = ["# typed: true", "# Generated declaration expression checks; never executed."]
          knowledge.local.select { |entry| entry["kind"] == "class" }.each do |entry|
            lines << "class #{entry['name']}"
            lines << "  extend T::Sig"
            entry["properties"].each do |property|
              lines << "  sig { returns(#{property['type']}) }"
              lines << "  def __spike_check_#{property['js']}"
              lines << property["expression"]
              lines << "  end"
            end
            lines << "end"
          end
          lines.join("\n") + "\n"
        end

    end
  end
end
