# frozen_string_literal: true

require "swill/core"
require "swill/transport"
require "swill/model/store"
require "swill/model/codec"
require "swill/model/codec/plain_json"
require "swill/model/drafts"
require "swill/model/attributes"
require "swill/model/dirty_tracking"
require "swill/model/identity"
require "swill/model/dataset"
require "swill/model/persistence"
require "swill/model/base"
require "swill/model/codec/json_api"
