# frozen_string_literal: true

require "swill/core"
require "swill/view/event"
require "swill/view/restoration"
require "swill/view/html_attributes"
require "swill/view/base"
require "swill/view/ownership"
require "swill/view/focus"
require "swill/view/outlets"
require "swill/view/bindings"
require "swill/view/actions"
require "swill/view/awakening"
require "swill/view/fragment_router"
require "swill/view/window"
require "swill/view/application"
